version: "3.8"

services:
  api:
    image: node:14
    container_name: dd_api
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./api:/usr/src/app
    command: sh -c "npm install && npm run dev"
    restart: always
    ports:
      - "8001:8001"
    depends_on:
      - mongo

  web:
    image: node:18
    container_name: dd_web
    working_dir: /usr/src/app
    volumes:
      - ./web:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "npm install && npm run start -- --host 0.0.0.0"
    restart: always
    ports:
      - "8000:4200"
    depends_on:
      - api

  mongo:
    image: mongo:latest
    container_name: dd_mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb

  mongo-express:
    image: mongo-express:latest
    container_name: dd_admin
    restart: always
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    ports:
      - "8002:8081"
    depends_on:
      - mongo

volumes:
  mongo_data:
    name: MONGO_DATA
  mongo_config:
    name: MONGO_CONFIG