export enum DamageType {
  bludgeoning = 'Bludgeoning',
  piercing = ' Piercing',
  slashing = 'Slashing',
  acid = 'Acid',
  cold = 'Cold',
  electricity = 'Electricity',
  fire = 'Fire',
  sonic = 'Sonic',
  positive = 'Positive',
  negative = 'Negative',
  force = 'Force',
  chaotic = 'Chaotic',
  evil = 'Evil',
  good = 'Good',
  lawful = 'Lawful',
  mental = 'Mental',
  poison = 'Poison',
  bleed = 'Bleed',
  precision = 'Precision',
}
