export enum WeaponGroup {
  axe = "Axe",
  battleaxe = "Battle axe",
  bomb = "Bomb",
  bow = "Bow",
  brawling = "Brawling",
  club = "Club",
  dart = "Dart",
  flail = "Flail",
  hammer = "Hammer",
  knife = "Knife",
  pick = "Pick",
  polearm = "Polearm",
  shield = "Shield",
  sling = "Sling",
  spear = "Spear",
  sword = "Sword",
  warhammer = "Warhammer",
  simple = "Simple",
  martial = "Martial",
  unarmed = "Unarmed",
}
